### ISSUE TITLE
appcenter-push crashes 8 - 10 seconds after app launches

### ISSUE THREAD

**Issue by flyingxu** [Microsoft/AppCenter-SDK-React-Native#207]
Hi, 

I added appcenter-push (together with several other appcenter package) into my react native app.

It compiles and run well but only for a short while. After about 10 seconds, the app crashes. I don't see any red error on react native debug or exception in Android Studio debug. But from the logcat, I see error like this:

`12-24 21:37:14.200 20815-20853/com.cdefghijk E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
	 Process: com.cdefghijk, PID: 20815
	 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
		 at android.content.ContextWrapper.getSystemService(ContextWrapper.java:719)
		 at com.google.firebase.iid.FirebaseInstanceIdService.zzby(Unknown Source)
		 at com.google.firebase.iid.FirebaseInstanceIdService.zzd(Unknown Source)
		 at com.google.firebase.iid.FirebaseInstanceIdService.zza(Unknown Source)
		 at com.google.firebase.iid.FirebaseInstanceIdService.zzm(Unknown Source)
		 at com.google.firebase.iid.zzb$2.run(Unknown Source)
		 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
		 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
		 at java.lang.Thread.run(Thread.java:762)`

It seems that it's related to FirebaseInstanceIdService not appcenter-push, I will try use other firebase package to see if there will be the same error.
The error occurs on both simulater and real device, and it can be reproduced every time.

Because it happens about 10s after app launch, is it related to network timeout and some service cannot be accessed?

**Comment by guperrot** [comment]
Hi, this is the Firebase library that crashes your app, not app center code.
Version 1.1.0 of the SDK can work without the Firebase library dependency.
To learn how to remove Firebase dependency: https://docs.microsoft.com/en-us/appcenter/sdk/push/migration/react-native-android
