### ISSUE TITLE
Make the SDK work with ReactXP

### ISSUE THREAD

**Issue by omatrot** [Microsoft/AppCenter-SDK-React-Native#337]
### **Description**

I'm using ReactXP and would like to use the AppCenter SDK.

### **Repro Steps**

Please list the steps used to reproduce your issue.

1. Clone the [ReactXP git repository](https://github.com/Microsoft/reactxp).
2. run `npm install` in a test project.
3. Follow the AppCenter's [Get Started SDK for iOS](https://appcenter.ms/users/olivier-matrot/apps/Hygeex-v2-iOS/).
4. The following error is encountered during `react-native link`

```
Oliviers-iMac:RXPHygeex omatrot$ react-native link
Scanning folders for symlinks in /Users/omatrot/Projects/hygeex/RXPHygeex/node_modules (44ms)
{ Error: Cannot find module '/Users/omatrot/Projects/hygeex/RXPHygeex/node_modules/react/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at getRNPMConfig (/Users/omatrot/Projects/hygeex/RXPHygeex/node_modules/react-native/local-cli/core/index.js:53:3)
    at Object.getDependencyConfig (/Users/omatrot/Projects/hygeex/RXPHygeex/node_modules/react-native/local-cli/core/index.js:115:18)
    at deps.reduce (/Users/omatrot/Projects/hygeex/RXPHygeex/node_modules/react-native/local-cli/link/getDependencyConfig.js:16:24)
    at Array.reduce (<anonymous>)
    at getDependencyConfig (/Users/omatrot/Projects/hygeex/RXPHygeex/node_modules/react-native/local-cli/link/getDependencyConfig.js:13:15)
    at Object.link (/Users/omatrot/Projects/hygeex/RXPHygeex/node_modules/react-native/local-cli/link/link.js:131:24) code: 'MODULE_NOT_FOUND' }
```
The process continues though.

### **Details**

1. Which SDK version are you using?
    - 1.6.0
2. Which OS version did you experience the issue on?
    - N/A
3. What device version did you see this error on?  Were you using an emulator or a physical device?
    - N/A
4. What third party libraries are you using?
    - ReactXP
5. Run the following command and paste the output below: `react-native info`

Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.11.2
  Yarn: 1.7.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.4.1 Build version 9F2000
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: 16.4.0 => Not Found
  react-native: ^0.55.4 => 0.55.4

6. If you're developing for React Native iOS, run the following command and paste the output below: `pod --version`

1.5.3

7. Please enable verbose logging for your app using `[MSAppCenter setLogLevel: MSLogLevelVerbose];` before your call to `[AppCenterReactNative register];` (or any other SDK registration). For Android, use `AppCenter.setLogLevel(android.util.Log.VERBOSE);` before your `SoLoader.init` call. Include the logs here:
N/A

**Comment by omatrot** [comment]
Solved by removing the node_modules folder and running `npm install`
