### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_AppCenterReactNativeCrashes", referenced from:

### ISSUE THREAD

**Issue by ldco2016** [microsoft/appcenter-sdk-react-native#588]
**Description**
Please describe the issue you are facing or a feature you would like to be added to the SDK.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AppCenterReactNativeCrashes", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)



** BUILD FAILED **



The following build commands failed:
    Ld /Users/danale/Library/Developer/Xcode/DerivedData/build/Build/Products/Debug-iphonesimulator/NFIBEngage.app/NFIBEngage normal x86_64
(1 failure)

Installing build/Build/Products/Debug-iphonesimulator/NFIBEngage.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/NFIBEngage.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Repro Steps
Please list the steps used to reproduce your issue.

I run `react-native run-ios`

Details
Which SDK version are you using?
e.g. 1.5.0
Which OS version did you experience the issue on?
iOS 10.13.6
What device version did you see this error on? Were you using an emulator or a physical device?
iPhone 6s
What third party libraries are you using?
react-native-onesignal
react-native-sentry
Run the following command and paste the output below: react-native info

```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 11.10.1
  Yarn: 1.10.1
  npm: 6.7.0
  Watchman: 4.7.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.4 AI-183.5429.30.34.5452501

Packages: (wanted => installed)
  react: 16.2.0 => 16.2.0
  react-native: 0.53.3 => 0.53.3
```

If you're developing for React Native iOS, run the following command and paste the output below:

```
pod --version
1.7.1
```

Please enable verbose logging for your app using [MSAppCenter setLogLevel: MSLogLevelVerbose]; before your call to [AppCenterReactNative register]; (or any other SDK registration). For Android, use AppCenter.setLogLevel(android.util.Log.VERBOSE); before your SoLoader.init call. Include the logs here:

Not sure how to do the above.

**Comment by AnastasiaKubova** [comment]
Hi, @ldco2016 . 
1. Make sure that Lib is added in your project. If this is missing please try adding it manually.
Build Phases -> Link Binary With Libraries the libAppCenterReactNativeCrashes.a
2. Try cleane and rebuild your project:
-  rm -rf ~/Library/Developer/Xcode/DerivedData/*
- Product -> Clean Build Folder
- Build from xcode

**Comment by ldco2016** [comment]
Greetings @AnastasiaKubova ,

When I add `libAppCenterReactNativeCrashes.a` to **Link Binary with Libraries** inside of **Build Phases**, Xcode crashes and when I reopen it, the `libAppCenterReactNativeCrashes.a` is not there. If I try to add it again, it just crashes again.

**Comment by AnastasiaKubova** [comment]
Hi, @ldco2016 ! Could you please provide pod file and output logs? Seems like one of the libraries is just missing.

**Comment by ldco2016** [comment]
Hi @AnastasiaKubova , yes the podfile looks like so:

```
# source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DEV' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DEV
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

end

target 'NFIBEngage-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NFIBEngage-tvOS



end

target 'PROD' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PROD
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

end

target 'QA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QA
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

end

target 'UA' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for UA
  pod 'AppCenter/Push', '~> 1.3.0'
  pod 'AppCenter/Crashes', '~> 1.3.0'
  pod 'AppCenter/Analytics', '~> 1.3.0'
  pod 'AppCenterReactNativeShared', '~> 1.2.0'

end

```

Just on the podfile above alone I am wondering if it should say `platform :ios, '9.0'`, neither my OSX nor my xcode are on ios 9 anything.  My Mac OSX is version 10.13.6 and my xcode is 10.1

Anyway, my pod install:

```
 pod install
Analyzing dependencies
Downloading dependencies
Using AppCenter (1.3.0)
Using AppCenterReactNativeShared (1.2.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 4 dependencies from the Podfile and 2 total pods installed.
```

**Comment by AnastasiaKubova** [comment]
Hi @ldco2016 , did you run 'react-native link' for our modules? Looks like 'AppCenterReactNativeCrashes' is not linked. It is done by our link script.

**Comment by ldco2016** [comment]
@AnastasiaKubova , when I run that command, it ultimately finishes with this error:

```
? Please select your project in Sentry: NFIB / NFIB Engage
Successfully set up android for react-native
/Users/danale/Projects/engage-application.mobile/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:267
            if (!script.shellScript.match(/(packager|scripts)\/react-native-xcode\.sh\b/) ||
                                    ^

TypeError: Cannot read property 'match' of undefined
    at ReactNative.patchExistingXcodeBuildScripts (/Users/danale/Projects/engage-application.mobile/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:267:37)
    at pbxProject.<anonymous> (/Users/danale/Projects/engage-application.mobile/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:333:23)
    at pbxProject.emit (events.js:197:13)
    at pbxProject.<anonymous> (/Users/danale/Projects/engage-application.mobile/node_modules/@sentry/wizard/node_modules/xcode/lib/pbxProject.js:48:18)
    at ChildProcess.emit (events.js:197:13)
    at emit (internal/child_process.js:834:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
/Users/danale/Projects/engage-application.mobile/node_modules/react-native/local-cli/core/makeCommand.js:29
        throw new Error(`Error occured during executing "${command}" command`);
        ^

Error: Error occured during executing "node node_modules/@sentry/wizard/dist/bin.js -t reactNative -p ios android" command
    at ChildProcess.prelink (/Users/danale/Projects/engage-application.mobile/node_modules/react-native/local-cli/core/makeCommand.js:29:15)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

Aside from this error, I am concerned that it does not mention that `ios` is setup successfully the same way it mentions it for Android.

**Comment by ldco2016** [comment]
The PhaseScriptExecution Strip\ Frameworks /appName.build/Debug-iphonesimulator/PROD.build/Script-8CBD27422B744FC9C0407AA3.sh Xcode build error was related to some configuration inside of ios/Pods/Pods.xcodeproj/project.pbxproj where the configuration in those files look something like this:

```
9B41C3B09EAC07B2B007DE0F /* Strip Frameworks */ = {
            isa = PBXShellScriptBuildPhase;
            buildActionMask = 2147483647;
            files = (
            );
            inputPaths = (
            );
            name = "Strip Frameworks";
            outputPaths = (
            );
            runOnlyForDeploymentPostprocessing = 0;
            shellPath = /bin/sh;
            shellScript = "bash \"${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/InstabugCore.framework/strip-frameworks.sh\"\n";
        };
```
Once I completely removed references to `8CBD27422B744FC9C0407AA3` the error went away and the error regarding `AppCenterReactNativeCrashes` was due to some configuration that while valid in terms of it being documented in AppCenter SDK docs, it was responsible for the consistent error and thus it was removed and reverted back to a previous configuration inside of `AppDelegate.m` file.
