### ISSUE TITLE
AppCenter build fails iOS

### ISSUE THREAD

**Issue by pjay79** [microsoft/appcenter-sdk-react-native#825]
Trying to run a build on app center and getting these errors in the logs, not sure what the workaround is. Do I need to add something to a build script?

```
2020-04-21T22:45:17.9459070Z failed to read project: React {
2020-04-21T22:45:17.9593480Z   error: Error: ENOENT: no such file or directory, open '/Users/runner/runners/2.166.3/work/1/s/node_modules/react-native/React/React.xcodeproj/project.pbxproj'
2020-04-21T22:45:17.9594320Z       at Object.openSync (fs.js:458:3)
2020-04-21T22:45:17.9594750Z       at Object.readFileSync (fs.js:360:35)
2020-04-21T22:45:17.9603360Z       at XcodeBuildsSettingsUpdater.<anonymous> (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/@build/xcproject-analyzer-script/script/xcode-builds-settings-updater.js:58:45)
2020-04-21T22:45:17.9604140Z       at Generator.next (<anonymous>)
2020-04-21T22:45:17.9620570Z       at fulfilled (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/@build/xcproject-analyzer-script/script/xcode-builds-settings-updater.js:4:58)
2020-04-21T22:45:17.9621930Z       at tryCatcher (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/util.js:16:23)
2020-04-21T22:45:17.9623270Z       at Promise._settlePromiseFromHandler (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:517:31)
2020-04-21T22:45:17.9644270Z       at Promise._settlePromise (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:574:18)
2020-04-21T22:45:17.9669930Z       at Promise._settlePromise0 (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:619:10)
2020-04-21T22:45:17.9671920Z       at Promise._settlePromises (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/promise.js:699:18)
2020-04-21T22:45:17.9673760Z       at _drainQueueStep (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:138:12)
2020-04-21T22:45:17.9675290Z       at _drainQueue (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:131:9)
2020-04-21T22:45:17.9676750Z       at Async._drainQueues (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:147:5)
2020-04-21T22:45:17.9678350Z       at Immediate.Async.drainQueues [as _onImmediate] (/Users/runner/runners/2.166.3/scripts/build-xcproject-analyzer/node_modules/bluebird/js/release/async.js:17:14)
2020-04-21T22:45:17.9679290Z       at processImmediate (internal/timers.js:456:21) {
2020-04-21T22:45:17.9680200Z     errno: -2,
2020-04-21T22:45:17.9681160Z     syscall: 'open',
2020-04-21T22:45:17.9682050Z     code: 'ENOENT',
2020-04-21T22:45:17.9683190Z     path: '/Users/runner/runners/2.166.3/work/1/s/node_modules/react-native/React/React.xcodeproj/project.pbxproj'
2020-04-21T22:45:17.9683700Z   }
2020-04-21T22:45:17.9684140Z }
```

`2020-04-21T22:49:06.3669390Z ##[error]Exit code 134 returned from process: file name '/Users/runner/runners/2.166.3/externals/node/bin/node', arguments '"/Users/runner/runners/2.166.3/work/_tasks/Xcode_1e78dc1b-9132-4b18-9c75-0e7ecc634b74/4.130.0/xcode.js"'.
`

**Comment by olmisa** [comment]
Hello @pjay79 
As mention in the issue template

> If your issue is related to App Center build only (meaning no issue building locally) or CodePush, please create an issue on https://github.com/Microsoft/appcenter instead.

In this case, I see that this issue is not related to this SDK, so could you please open a support ticket on the [https://appcenter.ms](https://appcenter.ms) portal ("?" menu in the top right corner and click on 'Contact support')?
If you think that it's App Center RN SDK issue, please fill the issue template (logs, versions, etc) instead of removing it.
