### ISSUE TITLE
Appcenter - Analytics Not working in React-native for android

### ISSUE THREAD

**Issue by XamBoy** [microsoft/appcenter-sdk-react-native#904]
"appcenter": "4.0.2",
    "appcenter-analytics": "4.0.2",
    "appcenter-crashes": "4.0.2",

  "react": "16.11.0",
    "react-native": "^0.62.2",

**Comment by russelarms** [comment]
@XamBoy please, feel in an issue template. To do that click [New issue](https://github.com/microsoft/appcenter-sdk-react-native/issues/new/choose) > [Problem report](https://github.com/microsoft/appcenter-sdk-react-native/issues/new?assignees=&labels=support&template=problem_report.md&title=)

In particular, we need detailed logs from your app: https://docs.microsoft.com/en-us/appcenter/sdk/other-apis/react-native#adjust-the-log-level

**Comment by XamBoy** [comment]
2021-03-17 12:38:42.393 25312-25312/com.daytontemplemobile D/AppCenter: Reading appcenter-config.json
2021-03-17 12:38:42.394 25312-25312/com.daytontemplemobile E/AppCenter: Failed to parse appcenter-config.json
    java.io.FileNotFoundException: appcenter-config.json
        at android.content.res.AssetManager.nativeOpenAsset(Native Method)
        at android.content.res.AssetManager.open(AssetManager.java:874)
        at android.content.res.AssetManager.open(AssetManager.java:851)
        at com.microsoft.appcenter.reactnative.shared.AppCenterReactNativeShared.readConfigurationFile(AppCenterReactNativeShared.java:66)
        at com.microsoft.appcenter.reactnative.shared.AppCenterReactNativeShared.configureAppCenter(AppCenterReactNativeShared.java:45)
        at com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativeModule.<init>(AppCenterReactNativeModule.java:28)
        at com.microsoft.appcenter.reactnative.appcenter.AppCenterReactNativePackage.<init>(AppCenterReactNativePackage.java:22)
        at com.facebook.react.PackageList.getPackages(PackageList.java:114)
        at com.daytontemplemobile.MainApplication$1.getPackages(MainApplication.java:45)
        at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:77)
        at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
        at com.daytontemplemobile.MainApplication.onCreate(MainApplication.java:67)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6712)
        at android.app.ActivityThread.access$1300(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1913)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by XamBoy** [comment]
Failed to parse appcenter-config.json
java.io.FileNotFoundException: appcenter-config.json
at android.content.res.AssetManager.nativeOpenAsset(Native Method)
at android.content.res.AssetManager.open(AssetManager.java:874)
at android.content.res.AssetManager.open(AssetManager.java:851)

**Comment by MatkovIvan** [comment]
@XamBoy please follow our getting started guide - https://docs.microsoft.com/en-us/appcenter/sdk/getting-started/react-native#312-integrate-react-native-android
